### ISSUE TITLE
Cannot get updates on arrival times

### ISSUE THREAD

**Issue by caldecy** [xuanyou/MMM-SG-Transport#1]
Thanks for uploading a module for Magic Mirror users in Singapore to get the latest arrival times! Fellow Singaporean here! :)

Anyway, after following your instructions to install the module, I still encounter a problem with displaying the bus arrival times in the Magic Mirror app. 

Config.js script as follows:

```
{
        		module: 'MMM-SG-Transport',
        		position: 'bottom_left',
        		config: {
            			lta_api_key: "<my API key inserted>",
            			refresh_interval: 5 * 1000,
            			bus_stops: [
                				{
                    					id: 63339,
                    					name: "Florence Road Bus Stop"
                				},
                				{
                    					id: 63331,
                    					name: "Opp Florence Road Bus Stop"
                				},
						{
							id: 63351,
							name: "Opp Swimming Complex"
						},
						{
							id: 63031,
							name: "Kovan Residences Bus Stop"
						}
            				  ]
        			}
    		},
```
However, upon running the Magic Mirror app and waiting for 2 minutes for all modules to successfully get updated, only this module remains as **Waiting for updates...**. 

A picture of the issue is attached:
![error](https://user-images.githubusercontent.com/33807640/33421048-c0af19da-d5eb-11e7-8c21-5f1c50909502.jpg)

I would kindly appreciate your help in advising me on how to get this module running smoothly! 

Thanks!

**Comment by xuanyou** [comment]
Hello! I have not updated the API to match LTA's v2 API. According to LTA, they took down the old v1 endpoint on 31 Oct 2017.

> *Changes in v2 API:*
> 
> 1. New Attribute – Bus ‘Type’
> 
> We are introducing a new attribute – vehicle type of oncoming bus(es)
> 
> - “SD” for Single Deck
> - "DD” for Double Deck
> - “BD” for Bendy
> 
> 2. Inclusion of Short Working Trip (SWT) Supplementary Services
> 
> SWTs are short haul supplementary services that cater to high demand segments along the service route instead of entire route, typically running during morning or evening peak hours. To make it easier for commuters to differentiate SWTs from its full-trip parent services, the Public Transport Operators (SBST, SMRT, TTS and GAS) have added a suffix to the service number, e.g. Service 72A is a short working trip of Service 72. Please note however, that the Route and Service Information (i.e. hours of operation) for SWTs are not available on DataMall.
> 
> 3. Removal of ‘SST’ Parameter
> 
> There will no longer be a need to supply the SST parameter to obtain bus arrival timestamps in SST format. All timestamps returned will now be in SST (GMT+08:00) by default.
> 
> 4. Relegation of ‘OriginCode’ and ‘DestinationCode’ to vehicle level
> 
> Formally known as OriginatingID and TerminatingID (renamed for consistency with other APIs), these two attributes are now brought down to the ‘vehicle-level’, i.e. each oncoming vehicle will now carry its own pair of Origin-Destination codes. As such, do expect up to three pairs of Origin-Destination values per service as it might differ from vehicle to vehicle. To retrieve the start-and-end stops of the entire service route, you may refer to the Bus Service API.
> 
> 5. Removal of entire response structure from API during non-operating hours
> 
> Please note that Bus Arrival data (i.e. all attribute-value pairs above) will only appear on the API when the service is in operation (i.e. on the roads). When not in operation, OR when the API service is undergoing maintenance and temporarily unavailable, there will be no response returned on the API (not even the attribute tags).
> 
> 6. Removal of ‘Status’ Attribute
> 
> Do refer to the user guide on how to display advisement messages when no response is returned on the API.
> 
> 7. Renaming of values for Load Attribute
> 
> ‘Seats Available’, ‘Standing Available’, and ‘Limited Standing’ has been renamed to ‘SEA’, ‘SDA’, and ‘LSD’ respectively.
> 
> 8. Renaming of ‘BusStopID’ Parameter to ‘BusStopCode’
> 
> Parameter has been renamed for consistency with other APIs.
> 
> 9. Renaming of ‘SubsequentBus’ and ‘SubsequentBus3’ subset tags
> 
> For better clarity, the subset tags have been renamed to ‘NextBus2’ and ‘NextBus3’.

The above changes would break the existing code.

I don't have a way to continue development, but you can fork/submit a pull request!
